import type { Organization, Campaign, Event, Member, Transaction, Donation, EventRegistration } from './types';

// ==============================================================================
// 1. ORGANISATION OFFICIELLE : ASSOCIATION ESPOIR CONGO (AEC)
// ==============================================================================
export const MOCK_ORGANIZATION: Organization = {
  id: 'e5555555-5555-5555-5555-555555555555',
  name: 'Association Espoir Congo',
  acronym: 'AEC',
  slug: 'espoir-congo',
  description: 'Organisation non gouvernementale dédiée à l\'éducation populaire, la santé communautaire et l\'insertion professionnelle des jeunes vulnérables à Brazzaville et dans le Pool.',
  province: 'Brazzaville',
  city: 'Brazzaville',
  address: 'Avenue de la Paix, Poto-Poto',
  phone: '+242 06 600 00 03',
  email: 'contact@espoircongo.cg',
  website: 'https://assocongo.crossroadsgroupsarlu.com/o/espoir-congo',
  logo_url: null,
  cover_url: null,
  legal_status: 'enregistree',
  registration_number: 'REC-BZV-2024-N048',
  domains: ['Éducation', 'Santé', 'Jeunesse'],
  status: 'active',
  is_verified: true,
  primary_color: '#009543',
  transparency_score: 96,
  deleted_at: null,
  created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
  updated_at: new Date().toISOString(),
};

export const MOCK_ORGANIZATIONS: Organization[] = [
  MOCK_ORGANIZATION,
  {
    id: 'e6666666-6666-6666-6666-666666666666',
    name: 'Solidarité Orphelins Pointe-Noire',
    acronym: 'SOPN',
    slug: 'orphelins-pnr',
    description: 'Prise en charge scolaire, nutritionnelle et médicale des orphelins et enfants en situation de rue dans le Kouilou.',
    province: 'Pointe-Noire',
    city: 'Pointe-Noire',
    address: 'Boulevard Denis Sassou Nguesso, Rond-Point Lumumba',
    phone: '+242 05 520 11 22',
    email: 'direction@orphelins-pnr.cg',
    website: 'https://assocongo.crossroadsgroupsarlu.com/o/orphelins-pnr',
    logo_url: null,
    cover_url: null,
    legal_status: 'enregistree',
    registration_number: 'REC-PNR-2023-A112',
    domains: ['Enfance', 'Action humanitaire', 'Nutrition'],
    status: 'active',
    is_verified: true,
    primary_color: '#FBDE4A',
    transparency_score: 92,
    deleted_at: null,
    created_at: new Date(Date.now() - 120 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'e7777777-7777-7777-7777-777777777777',
    name: 'Action Santé & Environnement Villageois',
    acronym: 'ASEV',
    slug: 'sante-environnement-pool',
    description: 'Campagnes médicales itinérantes, accès à l\'eau potable et reboisement communautaire dans le département du Pool.',
    province: 'Pool',
    city: 'Kinkala',
    address: 'Place du Marché Central, Kinkala',
    phone: '+242 06 630 44 55',
    email: 'contact@asev-pool.cg',
    website: 'https://assocongo.crossroadsgroupsarlu.com/o/sante-environnement-pool',
    logo_url: null,
    cover_url: null,
    legal_status: 'enregistree',
    registration_number: 'REC-POOL-2025-B007',
    domains: ['Santé', 'Environnement', 'Développement local'],
    status: 'active',
    is_verified: true,
    primary_color: '#009543',
    transparency_score: 88,
    deleted_at: null,
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// ==============================================================================
// 2. VENTILATION BUDGÉTAIRE DÉTAILLÉE : PROJET ÉCOLE BACONGO
// ==============================================================================
export interface BudgetItem {
  id: string;
  category: string;
  description: string;
  allocatedAmount: number; // Montant alloué (FCFA)
  spentAmount: number;     // Montant engagé / dépensé (FCFA)
  percentageSpent: number;
  provider: string;        // Prestataire / Artisan local
  invoiceRef: string;      // Référence facture / bon de commande
  status: 'completed' | 'in_progress' | 'planned';
}

export const BUDGET_BREAKDOWN_BACONGO: BudgetItem[] = [
  {
    id: 'b1',
    category: 'Menuiserie & Mobilier scolaire',
    description: 'Fabrication de 120 tables-bancs doubles en bois rouge local (Iroko) pour équiper 4 salles de classe.',
    allocatedAmount: 1200000,
    spentAmount: 1000000,
    percentageSpent: 83,
    provider: 'Artisans Menuisiers de Bacongo (Coopérative Rue Mbaka)',
    invoiceRef: 'FAC-2026-AMB-042',
    status: 'in_progress',
  },
  {
    id: 'b2',
    category: 'Toiture, Charpente & Étanchéité',
    description: 'Remplacement de 85 tôles bac galvanisées et réfection de la charpente endommagée par les intempéries.',
    allocatedAmount: 650000,
    spentAmount: 500000,
    percentageSpent: 77,
    provider: 'Quincaillerie Centrale Poto-Poto / Société BTP Congo',
    invoiceRef: 'FAC-2026-QCP-118',
    status: 'completed',
  },
  {
    id: 'b3',
    category: 'Peinture lavable & Tableaux noirs',
    description: 'Enduit des murs intérieurs/extérieurs et application de peinture ardoise haute durabilité pour tableaux scolaires.',
    allocatedAmount: 450000,
    spentAmount: 350000,
    percentageSpent: 78,
    provider: 'Entreprise Peinture Pro Brazzaville',
    invoiceRef: 'FAC-2026-EPB-089',
    status: 'completed',
  },
  {
    id: 'b4',
    category: 'Bloc Sanitaire & Hygiène',
    description: 'Réhabilitation de 2 latrines VIP écologiques avec point d\'eau lave-mains pour 280 écoliers.',
    allocatedAmount: 500000,
    spentAmount: 300000,
    percentageSpent: 60,
    provider: 'Assainissement Solidaire Congo',
    invoiceRef: 'FAC-2026-ASC-015',
    status: 'in_progress',
  },
  {
    id: 'b5',
    category: 'Logistique, Transport & Suivi technique',
    description: 'Transport sécurisé des matériaux et indemnités de coordination du comité de suivi des parents d\'élèves.',
    allocatedAmount: 200000,
    spentAmount: 0,
    percentageSpent: 0,
    provider: 'Comité de Gestion École de Bacongo',
    invoiceRef: 'ENG-2026-CGE-001',
    status: 'planned',
  },
];

// ==============================================================================
// 3. CAMPAGNES COHÉRENTES AU FRANC PRÈS
// ==============================================================================
export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'f6666666-6666-6666-6666-666666666666',
    organization_id: MOCK_ORGANIZATION.id,
    title: 'Rénovation et équipement de l\'école primaire de Bacongo',
    slug: 'renovation-ecole-bacongo',
    description: 'Réhabilitation de 4 salles de classe dégradées, achat de 120 tables-bancs en bois local et installation de latrines écologiques pour 280 écoliers du quartier Bacongo à Brazzaville.',
    image_url: null,
    goal_amount: 3000000,
    current_amount: 2150000, // Exactement 2 150 000 FCFA (somme des dons 1 à 5)
    currency: 'XAF',
    category: 'Éducation',
    status: 'active',
    is_featured: true,
    start_date: new Date(Date.now() - 30 * 86400000).toISOString(),
    end_date: new Date(Date.now() + 25 * 86400000).toISOString(),
    deleted_at: null,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'f7777777-7777-7777-7777-777777777777',
    organization_id: MOCK_ORGANIZATION.id,
    title: 'Bourses numériques pour 50 jeunes filles à Brazzaville',
    slug: 'bourses-numeriques-filles',
    description: 'Financement de formations accélérées au développement web, bureautique et marketing digital à l\'Université Marien Ngouabi pour faciliter l\'insertion professionnelle.',
    image_url: null,
    goal_amount: 1500000,
    current_amount: 1120000, // Exactement 1 120 000 FCFA (somme des dons 6 à 9)
    currency: 'XAF',
    category: 'Jeunesse',
    status: 'active',
    is_featured: false,
    start_date: new Date(Date.now() - 20 * 86400000).toISOString(),
    end_date: new Date(Date.now() + 40 * 86400000).toISOString(),
    deleted_at: null,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'f8888888-8888-8888-8888-888888888888',
    organization_id: MOCK_ORGANIZATION.id,
    title: 'Kits scolaires et santé pour 200 enfants de Talangaï',
    slug: 'kits-scolaires-talangai',
    description: 'Fourniture de manuels scolaires, cahiers, cartables et trousses de premiers soins pour la rentrée des classes dans le 6e arrondissement de Brazzaville.',
    image_url: null,
    goal_amount: 1500000,
    current_amount: 1500000, // Objectif atteint à 100%
    currency: 'XAF',
    category: 'Éducation',
    status: 'completed',
    is_featured: true,
    start_date: new Date(Date.now() - 60 * 86400000).toISOString(),
    end_date: new Date(Date.now() - 5 * 86400000).toISOString(),
    deleted_at: null,
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// ==============================================================================
// 4. ÉVÉNEMENTS COMMUNAUTAIRES RÉELS
// ==============================================================================
export const MOCK_EVENTS: Event[] = [
  {
    id: 'd1111111-1111-1111-1111-111111111111',
    organization_id: MOCK_ORGANIZATION.id,
    title: 'Grande dictée solidaire et distribution de manuels scolaires',
    slug: 'grande-dictee-solidaire-bacongo',
    description: 'Événement culturel et éducatif réunissant 200 élèves des écoles de Bacongo et Makélékélé avec remise de prix d\'excellence et de dictionnaires.',
    image_url: null,
    venue: 'Maison Commune de Bacongo',
    location: 'Place de la Mairie, Bacongo, Brazzaville',
    start_date: new Date(Date.now() + 12 * 86400000).toISOString(),
    end_date: new Date(Date.now() + 12 * 86400000 + 4 * 3600000).toISOString(),
    capacity: 200,
    registration_fee: 0,
    currency: 'XAF',
    status: 'active',
    is_public: true,
    deleted_at: null,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'd2222222-2222-2222-2222-222222222222',
    organization_id: MOCK_ORGANIZATION.id,
    title: 'Atelier d\'initiation au code et à la robotique pour ados',
    slug: 'atelier-code-robotique-jeunes',
    description: 'Formation pratique gratuite le samedi matin pour 30 jeunes filles et garçons de Moungali et Ouenzé pour découvrir la programmation informatique.',
    image_url: null,
    venue: 'Centre Culturel Sony Labou Tansi',
    location: 'Avenue de la Paix, Brazzaville',
    start_date: new Date(Date.now() + 20 * 86400000).toISOString(),
    end_date: new Date(Date.now() + 20 * 86400000 + 3 * 3600000).toISOString(),
    capacity: 30,
    registration_fee: 0,
    currency: 'XAF',
    status: 'active',
    is_public: true,
    deleted_at: null,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// ==============================================================================
// 5. PARTICIPANTS INSCRITS AVEC ÉMARGEMENT (CHECK-IN)
// ==============================================================================
export const MOCK_EVENT_REGISTRATIONS: EventRegistration[] = [
  {
    id: 'reg-grace-01',
    event_id: 'd1111111-1111-1111-1111-111111111111',
    organization_id: MOCK_ORGANIZATION.id,
    participant_name: 'Grace Moukassa',
    participant_email: 'adherent@espoircongo.cg',
    participant_phone: '+242 05 500 00 04',
    status: 'confirmed',
    payment_status: 'free',
    checked_in_at: null,
    deleted_at: null,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'reg-001',
    event_id: 'd1111111-1111-1111-1111-111111111111',
    organization_id: MOCK_ORGANIZATION.id,
    participant_name: 'Chancelle Okemba',
    participant_email: 'c.okemba@ecole-bacongo.cg',
    participant_phone: '+242 06 615 22 11',
    status: 'checked_in', // Déjà émargé à l'entrée
    payment_status: 'free',
    checked_in_at: new Date().toISOString(),
    deleted_at: null,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'reg-002',
    event_id: 'd1111111-1111-1111-1111-111111111111',
    organization_id: MOCK_ORGANIZATION.id,
    participant_name: 'Guy-Roger Malonga',
    participant_email: 'gr.malonga@gmail.com',
    participant_phone: '+242 05 520 44 33',
    status: 'checked_in',
    payment_status: 'free',
    checked_in_at: new Date().toISOString(),
    deleted_at: null,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'reg-003',
    event_id: 'd1111111-1111-1111-1111-111111111111',
    organization_id: MOCK_ORGANIZATION.id,
    participant_name: 'Prince Mikala (Étudiant UMNG)',
    participant_email: 'prince.mikala@umng.cg',
    participant_phone: '+242 04 430 11 99',
    status: 'confirmed',
    payment_status: 'free',
    checked_in_at: null,
    deleted_at: null,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'reg-004',
    event_id: 'd1111111-1111-1111-1111-111111111111',
    organization_id: MOCK_ORGANIZATION.id,
    participant_name: 'Raïssa Ngoma (Élève CM2)',
    participant_email: 'parent.ngoma@yahoo.fr',
    participant_phone: '+242 06 688 77 44',
    status: 'confirmed',
    payment_status: 'free',
    checked_in_at: null,
    deleted_at: null,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'reg-005',
    event_id: 'd1111111-1111-1111-1111-111111111111',
    organization_id: MOCK_ORGANIZATION.id,
    participant_name: 'Fabrice Bounda (Parent d\'élève Makélékélé)',
    participant_email: 'bounda.f@gmail.com',
    participant_phone: '+242 05 512 88 00',
    status: 'confirmed',
    payment_status: 'free',
    checked_in_at: null,
    deleted_at: null,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// ==============================================================================
// 6. MEMBRES DU CRM AVEC CARTES ET COTISATIONS 2026
// ==============================================================================
export const MOCK_MEMBERS: Member[] = [
  {
    id: 'm1111111-1111-1111-1111-111111111111',
    organization_id: MOCK_ORGANIZATION.id,
    first_name: 'Marien',
    last_name: 'Ngouabi',
    email: 'contact@espoircongo.cg',
    phone: '+242 06 600 00 03',
    birth_date: '1979-05-18',
    gender: 'M',
    address: 'Avenue de la Paix, Poto-Poto',
    city: 'Brazzaville',
    province: 'Brazzaville',
    membership_type: 'board',
    membership_fee: 25000,
    membership_status: 'active',
    membership_start: '2026-01-01',
    membership_end: '2026-12-31',
    card_number: 'CG-BZV-2026-00001',
    notes: 'Président fondateur - Cotisation annuelle acquittée via MTN MoMo',
    deleted_at: null,
    created_at: new Date(Date.now() - 80 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'm2222222-2222-2222-2222-222222222222',
    organization_id: MOCK_ORGANIZATION.id,
    first_name: 'Carine',
    last_name: 'Massamba',
    email: 'carine.massamba@yahoo.fr',
    phone: '+242 04 423 45 67',
    birth_date: '1984-02-18',
    gender: 'F',
    address: 'Avenue de la Base',
    city: 'Brazzaville',
    province: 'Brazzaville',
    membership_type: 'board',
    membership_fee: 25000,
    membership_status: 'active',
    membership_start: '2026-01-01',
    membership_end: '2026-12-31',
    card_number: 'CG-BZV-2026-00002',
    notes: 'Secrétaire Générale - Cotisation acquittée via Airtel Money',
    deleted_at: null,
    created_at: new Date(Date.now() - 75 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'm3333333-3333-3333-3333-333333333333',
    organization_id: MOCK_ORGANIZATION.id,
    first_name: 'Grace',
    last_name: 'Moukassa',
    email: 'adherent@espoircongo.cg',
    phone: '+242 05 500 00 04',
    birth_date: '1995-04-12',
    gender: 'F',
    address: 'Rue Mbaka, Bacongo',
    city: 'Brazzaville',
    province: 'Brazzaville',
    membership_type: 'volunteer',
    membership_fee: 10000,
    membership_status: 'active',
    membership_start: '2026-01-15',
    membership_end: '2026-12-31',
    card_number: 'CG-BZV-2026-00101',
    notes: 'Animatrice pédagogique bénévole responsable du soutien scolaire à Bacongo',
    deleted_at: null,
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'm4444444-4444-4444-4444-444444444444',
    organization_id: MOCK_ORGANIZATION.id,
    first_name: 'Arsène',
    last_name: 'Loundou',
    email: 'arsene.loundou@gmail.com',
    phone: '+242 06 612 34 56',
    birth_date: '1988-09-22',
    gender: 'M',
    address: 'Boulevard Denis Sassou Nguesso',
    city: 'Brazzaville',
    province: 'Brazzaville',
    membership_type: 'member',
    membership_fee: 15000,
    membership_status: 'active',
    membership_start: '2026-01-10',
    membership_end: '2026-12-31',
    card_number: 'CG-BZV-2026-00102',
    notes: 'Adhérent actif - Cotisation annuelle réglée via MTN MoMo (*105#)',
    deleted_at: null,
    created_at: new Date(Date.now() - 55 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'm5555555-5555-5555-5555-555555555555',
    organization_id: MOCK_ORGANIZATION.id,
    first_name: 'Dieudonné',
    last_name: 'Nzamba',
    email: 'dieu.nzamba@hotmail.com',
    phone: '+242 06 655 78 90',
    birth_date: '1992-11-05',
    gender: 'M',
    address: 'Avenue des 3 Martyrs, Poto-Poto',
    city: 'Brazzaville',
    province: 'Brazzaville',
    membership_type: 'member',
    membership_fee: 15000,
    membership_status: 'active',
    membership_start: '2026-02-01',
    membership_end: '2026-12-31',
    card_number: 'CG-BZV-2026-00103',
    notes: 'Adhérent actif - Cotisation réglée via Airtel Money (*128#)',
    deleted_at: null,
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'm6666666-6666-6666-6666-666666666666',
    organization_id: MOCK_ORGANIZATION.id,
    first_name: 'Priscille',
    last_name: 'Bikoumou',
    email: 'priscille.b@gmail.com',
    phone: '+242 05 533 11 22',
    birth_date: '1999-07-30',
    gender: 'F',
    address: 'Quartier Moungali III',
    city: 'Brazzaville',
    province: 'Brazzaville',
    membership_type: 'volunteer',
    membership_fee: 10000,
    membership_status: 'active',
    membership_start: '2026-03-01',
    membership_end: '2026-12-31',
    card_number: 'CG-BZV-2026-00104',
    notes: 'Chargée de communication réseaux sociaux et mobilisation des jeunes',
    deleted_at: null,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// ==============================================================================
// 7. DONS ENTRANTS EXACTEMENT ÉQUILIBRÉS AUX CAMPAGNES
// ==============================================================================
export const MOCK_DONATIONS: Donation[] = [
  // --- Dons pour Projet Bacongo (Total: 2 150 000 FCFA) ---
  {
    id: 'don-001',
    organization_id: MOCK_ORGANIZATION.id,
    campaign_id: 'f6666666-6666-6666-6666-666666666666',
    donor_name: 'Sylvain Batéké (Société BTP Congo)',
    donor_email: 'sylvain.bateke@btp-congo.cg',
    donor_phone: '+242 06 611 00 22',
    donor_is_anonymous: false,
    amount: 1000000,
    tip_amount: 15000,
    currency: 'XAF',
    message: 'Notre entreprise soutient fièrement la réfection des salles de classe de Bacongo pour les enfants de la République !',
    status: 'completed',
    payment_provider: 'mtn_momo',
    receipt_number: 'REC-DGIFN-2026-004812',
    receipt_sent: true,
    deleted_at: null,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'don-002',
    organization_id: MOCK_ORGANIZATION.id,
    campaign_id: 'f6666666-6666-6666-6666-666666666666',
    donor_name: 'Dr. Christian Mabiala',
    donor_email: 'mabiala.doc@cg-sante.org',
    donor_phone: '+242 06 612 00 99',
    donor_is_anonymous: false,
    amount: 500000,
    tip_amount: 5000,
    currency: 'XAF',
    message: 'Don institutionnel dédié en priorité à la construction des latrines écologiques et à l\'hygiène des élèves.',
    status: 'completed',
    payment_provider: 'cash',
    receipt_number: 'REC-DGIFN-2026-004813',
    receipt_sent: true,
    deleted_at: null,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'don-003',
    organization_id: MOCK_ORGANIZATION.id,
    campaign_id: 'f6666666-6666-6666-6666-666666666666',
    donor_name: 'Collecte des Anciens Élèves de Bacongo',
    donor_email: 'anciens.bacongo@gmail.com',
    donor_phone: '+242 06 655 44 33',
    donor_is_anonymous: false,
    amount: 350000,
    tip_amount: 3500,
    currency: 'XAF',
    message: 'Solidarité intergénérationnelle pour notre ancienne école primaire.',
    status: 'completed',
    payment_provider: 'mtn_momo',
    receipt_number: 'REC-DGIFN-2026-004814',
    receipt_sent: true,
    deleted_at: null,
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'don-004',
    organization_id: MOCK_ORGANIZATION.id,
    campaign_id: 'f6666666-6666-6666-6666-666666666666',
    donor_name: 'Patrick Mouyabi',
    donor_email: 'patrick.mouyabi@gmail.com',
    donor_phone: '+242 04 422 33 44',
    donor_is_anonymous: false,
    amount: 200000,
    tip_amount: 2000,
    currency: 'XAF',
    message: 'Bravo pour la transparence et le suivi sur la plateforme AssoCongo.',
    status: 'completed',
    payment_provider: 'airtel_money',
    receipt_number: 'REC-DGIFN-2026-004815',
    receipt_sent: true,
    deleted_at: null,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'don-005',
    organization_id: MOCK_ORGANIZATION.id,
    campaign_id: 'f6666666-6666-6666-6666-666666666666',
    donor_name: 'Mécène Anonyme Poto-Poto',
    donor_email: null,
    donor_phone: '+242 06 644 55 66',
    donor_is_anonymous: true,
    amount: 100000,
    tip_amount: 1000,
    currency: 'XAF',
    message: 'Pour l\'achat des tables-bancs en bois.',
    status: 'completed',
    payment_provider: 'mtn_momo',
    receipt_number: 'REC-DGIFN-2026-004816',
    receipt_sent: true,
    deleted_at: null,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // --- Dons pour Projet Bourses Numériques (Total: 1 120 000 FCFA) ---
  {
    id: 'don-006',
    organization_id: MOCK_ORGANIZATION.id,
    campaign_id: 'f7777777-7777-7777-7777-777777777777',
    donor_name: 'Fondation MTN Congo (RSE)',
    donor_email: 'rse.congo@mtn.com',
    donor_phone: '+242 06 600 99 00',
    donor_is_anonymous: false,
    amount: 600000,
    tip_amount: 10000,
    currency: 'XAF',
    message: 'Partenariat pour l\'inclusion numérique et l\'autonomisation des jeunes filles congolaises.',
    status: 'completed',
    payment_provider: 'mtn_momo',
    receipt_number: 'REC-DGIFN-2026-004820',
    receipt_sent: true,
    deleted_at: null,
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'don-007',
    organization_id: MOCK_ORGANIZATION.id,
    campaign_id: 'f7777777-7777-7777-7777-777777777777',
    donor_name: 'Collectif Femmes Cadres de Brazzaville',
    donor_email: 'femmes.cadres@cg-cadres.org',
    donor_phone: '+242 04 455 66 77',
    donor_is_anonymous: false,
    amount: 300000,
    tip_amount: 3000,
    currency: 'XAF',
    message: 'Pour encourager l\'excellence féminine dans les filières scientifiques et technologiques.',
    status: 'completed',
    payment_provider: 'airtel_money',
    receipt_number: 'REC-DGIFN-2026-004821',
    receipt_sent: true,
    deleted_at: null,
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'don-008',
    organization_id: MOCK_ORGANIZATION.id,
    campaign_id: 'f7777777-7777-7777-7777-777777777777',
    donor_name: 'Nathalie Loubaki',
    donor_email: 'n.loubaki@yahoo.fr',
    donor_phone: '+242 06 633 22 11',
    donor_is_anonymous: false,
    amount: 150000,
    tip_amount: 1500,
    currency: 'XAF',
    message: 'Félicitations pour ce projet d\'avenir !',
    status: 'completed',
    payment_provider: 'mtn_momo',
    receipt_number: 'REC-DGIFN-2026-004822',
    receipt_sent: true,
    deleted_at: null,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'don-009',
    organization_id: MOCK_ORGANIZATION.id,
    campaign_id: 'f7777777-7777-7777-7777-777777777777',
    donor_name: 'Amicale des Étudiants UMNG',
    donor_email: 'amicale.umng@gmail.com',
    donor_phone: '+242 04 422 99 88',
    donor_is_anonymous: false,
    amount: 70000,
    tip_amount: 1000,
    currency: 'XAF',
    message: 'Soutien fraternel aux boursières de l\'université.',
    status: 'completed',
    payment_provider: 'airtel_money',
    receipt_number: 'REC-DGIFN-2026-004823',
    receipt_sent: true,
    deleted_at: null,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'don-grace-01',
    organization_id: MOCK_ORGANIZATION.id,
    campaign_id: 'f6666666-6666-6666-6666-666666666666',
    donor_name: 'Grace Moukassa',
    donor_email: 'adherent@espoircongo.cg',
    donor_phone: '+242 05 500 00 04',
    donor_is_anonymous: false,
    amount: 25000,
    tip_amount: 1000,
    currency: 'XAF',
    message: 'Soutien de cœur pour la réfection des salles de classe de l\'école de Bacongo. Ensemble pour nos élèves !',
    status: 'completed',
    payment_provider: 'mtn_momo',
    receipt_number: 'REC-DGIFN-2026-004825',
    receipt_sent: true,
    deleted_at: null,
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// ==============================================================================
// 8. TRANSACTIONS ENTRANTES ET SORTANTES (AVEC REVERSEMENT BANCAIRE)
// ==============================================================================
export const MOCK_TRANSACTIONS: Transaction[] = [
  // Reversement bancaire sortant (Reversement des dons collectés vers la banque de l'ONG)
  {
    id: 'txn-payout-001',
    organization_id: MOCK_ORGANIZATION.id,
    donation_id: null,
    event_registration_id: null,
    type: 'payout',
    amount: 1800000,
    currency: 'XAF',
    status: 'success',
    provider: 'other',
    provider_reference: 'VIR-UBA-BZV-2026-00412',
    provider_transaction_id: 'BANK-UBA-CG-00412',
    provider_phone: '+242 06 600 00 03',
    description: 'Reversement bancaire certifié DGIFN vers compte UBA Congo AEC (N° CG023 00101 02000014820 45) - Règlement acompte 120 tables-bancs Bacongo',
    metadata: { bank: 'UBA Congo', iban: 'CG023 00101 02000014820 45', beneficiary: 'Association Espoir Congo' },
    deleted_at: null,
    processed_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Don Mécène BTP Bacongo
  {
    id: 'txn-001',
    organization_id: MOCK_ORGANIZATION.id,
    donation_id: 'don-001',
    event_registration_id: null,
    type: 'donation',
    amount: 1000000,
    currency: 'XAF',
    status: 'success',
    provider: 'mtn_momo',
    provider_reference: 'MOMO-CG-2026-98441',
    provider_transaction_id: 'TXN-MTN-98441',
    provider_phone: '+242 06 611 00 22',
    description: 'Don mécène pour réfection école primaire Bacongo via MTN MoMo (*105#)',
    metadata: {},
    deleted_at: null,
    processed_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Don Fondation MTN Bourses Filles
  {
    id: 'txn-002',
    organization_id: MOCK_ORGANIZATION.id,
    donation_id: 'don-006',
    event_registration_id: null,
    type: 'donation',
    amount: 600000,
    currency: 'XAF',
    status: 'success',
    provider: 'mtn_momo',
    provider_reference: 'MOMO-CG-2026-99001',
    provider_transaction_id: 'TXN-MTN-99001',
    provider_phone: '+242 06 600 99 00',
    description: 'Subvention RSE bourses numériques filles via MTN MoMo',
    metadata: {},
    deleted_at: null,
    processed_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Don Dr. Christian Mabiala (Espèces avec reçu certifié)
  {
    id: 'txn-003',
    organization_id: MOCK_ORGANIZATION.id,
    donation_id: 'don-002',
    event_registration_id: null,
    type: 'donation',
    amount: 500000,
    currency: 'XAF',
    status: 'success',
    provider: 'cash',
    provider_reference: 'REC-CSH-BZV-0019',
    provider_transaction_id: 'TXN-CSH-0019',
    provider_phone: '+242 06 612 00 99',
    description: 'Don sanitaire pour latrines Bacongo avec reçu physique certifié DGIFN',
    metadata: {},
    deleted_at: null,
    processed_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Don Collecte Anciens Élèves Bacongo
  {
    id: 'txn-004',
    organization_id: MOCK_ORGANIZATION.id,
    donation_id: 'don-003',
    event_registration_id: null,
    type: 'donation',
    amount: 350000,
    currency: 'XAF',
    status: 'success',
    provider: 'mtn_momo',
    provider_reference: 'MOMO-CG-2026-98219',
    provider_transaction_id: 'TXN-MTN-98219',
    provider_phone: '+242 06 655 44 33',
    description: 'Collecte solidaire anciens élèves école de Bacongo via MTN MoMo',
    metadata: {},
    deleted_at: null,
    processed_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Don Femmes Cadres Bourses Filles
  {
    id: 'txn-005',
    organization_id: MOCK_ORGANIZATION.id,
    donation_id: 'don-007',
    event_registration_id: null,
    type: 'donation',
    amount: 300000,
    currency: 'XAF',
    status: 'success',
    provider: 'airtel_money',
    provider_reference: 'AIRTEL-CG-2026-78110',
    provider_transaction_id: 'TXN-ART-78110',
    provider_phone: '+242 04 455 66 77',
    description: 'Don solidaire bourses numériques filles via Airtel Money (*128#)',
    metadata: {},
    deleted_at: null,
    processed_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Don Patrick Mouyabi
  {
    id: 'txn-006',
    organization_id: MOCK_ORGANIZATION.id,
    donation_id: 'don-004',
    event_registration_id: null,
    type: 'donation',
    amount: 200000,
    currency: 'XAF',
    status: 'success',
    provider: 'airtel_money',
    provider_reference: 'AIRTEL-CG-2026-88210',
    provider_transaction_id: 'TXN-ART-88210',
    provider_phone: '+242 04 422 33 44',
    description: 'Don particulier école Bacongo via Airtel Money',
    metadata: {},
    deleted_at: null,
    processed_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Don Nathalie Loubaki
  {
    id: 'txn-007',
    organization_id: MOCK_ORGANIZATION.id,
    donation_id: 'don-008',
    event_registration_id: null,
    type: 'donation',
    amount: 150000,
    currency: 'XAF',
    status: 'success',
    provider: 'mtn_momo',
    provider_reference: 'MOMO-CG-2026-97652',
    provider_transaction_id: 'TXN-MTN-97652',
    provider_phone: '+242 06 633 22 11',
    description: 'Don individuel formation jeunes filles via MTN MoMo',
    metadata: {},
    deleted_at: null,
    processed_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Don Mécène Anonyme
  {
    id: 'txn-008',
    organization_id: MOCK_ORGANIZATION.id,
    donation_id: 'don-005',
    event_registration_id: null,
    type: 'donation',
    amount: 100000,
    currency: 'XAF',
    status: 'success',
    provider: 'mtn_momo',
    provider_reference: 'MOMO-CG-2026-98124',
    provider_transaction_id: 'TXN-MTN-98124',
    provider_phone: '+242 06 644 55 66',
    description: 'Don anonyme Poto-Poto pour école Bacongo via MTN MoMo',
    metadata: {},
    deleted_at: null,
    processed_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Cotisation Bureau Carine Massamba
  {
    id: 'txn-009',
    organization_id: MOCK_ORGANIZATION.id,
    donation_id: null,
    event_registration_id: null,
    type: 'membership_fee',
    amount: 25000,
    currency: 'XAF',
    status: 'success',
    provider: 'airtel_money',
    provider_reference: 'AIRTEL-CG-2026-77810',
    provider_transaction_id: 'TXN-ART-77810',
    provider_phone: '+242 04 423 45 67',
    description: 'Cotisation annuelle 2026 - Secrétaire Générale (Carine Massamba)',
    metadata: {},
    deleted_at: null,
    processed_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Cotisation Membre Arsène Loundou
  {
    id: 'txn-010',
    organization_id: MOCK_ORGANIZATION.id,
    donation_id: null,
    event_registration_id: null,
    type: 'membership_fee',
    amount: 15000,
    currency: 'XAF',
    status: 'success',
    provider: 'mtn_momo',
    provider_reference: 'MOMO-CG-2026-96101',
    provider_transaction_id: 'TXN-MTN-96101',
    provider_phone: '+242 06 612 34 56',
    description: 'Adhésion annuelle membre actif 2026 (Arsène Loundou)',
    metadata: {},
    deleted_at: null,
    processed_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Don Solidaire Grace Moukassa
  {
    id: 'txn-grace-don-01',
    organization_id: MOCK_ORGANIZATION.id,
    donation_id: 'don-grace-01',
    event_registration_id: null,
    type: 'donation',
    amount: 25000,
    currency: 'XAF',
    status: 'success',
    provider: 'mtn_momo',
    provider_reference: 'MOMO-CG-2026-99312',
    provider_transaction_id: 'TXN-MTN-99312',
    provider_phone: '+242 05 500 00 04',
    description: 'Don solidaire réfection école Bacongo - Grace Moukassa',
    metadata: {},
    deleted_at: null,
    processed_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Cotisation Annuelle Grace Moukassa
  {
    id: 'txn-grace-cotis-01',
    organization_id: MOCK_ORGANIZATION.id,
    donation_id: null,
    event_registration_id: null,
    type: 'membership_fee',
    amount: 10000,
    currency: 'XAF',
    status: 'success',
    provider: 'mtn_momo',
    provider_reference: 'MOMO-CG-2026-96041',
    provider_transaction_id: 'TXN-MTN-96041',
    provider_phone: '+242 05 500 00 04',
    description: 'Cotisation statutaire annuelle adhérent 2026 (Grace Moukassa)',
    metadata: {},
    deleted_at: null,
    processed_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];
